# Generated by Django 5.0.3 on 2024-05-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0003_producthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="defaul name", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos"),
        ),
    ]
