# Generated by Django 5.0.3 on 2024-05-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0004_customuser_name_customuser_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mahsulot",
            name="massa",
            field=models.FloatField(default=0),
        ),
    ]
