# Generated by Django 5.0.3 on 2024-07-26 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0005_alter_mahsulot_massa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producthistory",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="producthistory",
            name="product_id",
        ),
        migrations.AddField(
            model_name="producthistory",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="history",
                to="warehouse.customer",
            ),
        ),
        migrations.AddField(
            model_name="producthistory",
            name="product",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="warehouse.mahsulot",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="producthistory",
            name="transaction_type",
            field=models.CharField(
                choices=[("ADD", "Added"), ("SEND", "Sent to Customer")], max_length=10
            ),
        ),
    ]
