# Generated by Django 5.0.3 on 2024-05-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectrodeLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ElectrodeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electrode.electrodelabel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Electrode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package", models.IntegerField(blank=True, default=0, null=True)),
                ("box", models.IntegerField(blank=True, default=0, null=True)),
                ("weight", models.FloatField(blank=True, default=0, null=True)),
                (
                    "count_by_label",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("added_date", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electrode.electrodecategory",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electrode.electrodelabel",
                    ),
                ),
            ],
        ),
    ]
