# Generated by Django 5.0.3 on 2024-05-13 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("electrode", "0002_remove_electrodecategory_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="electrodecategory",
            name="label",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="electrode.electrodelabel",
            ),
            preserve_default=False,
        ),
    ]
