# Generated by Django 5.0.3 on 2024-05-15 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("electrode", "0003_electrodecategory_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electrode",
            name="count_by_label",
        ),
    ]
