# Generated by Django 5.0.3 on 2024-07-04 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("electrode", "0005_electrodehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electrodehistory",
            name="electrode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="electrode.electrode"
            ),
        ),
        migrations.AlterField(
            model_name="electrodehistory",
            name="transaction_type",
            field=models.CharField(
                choices=[("ADD", "Added"), ("SEND", "Sent to Customer")], max_length=10
            ),
        ),
    ]
