# Generated by Django 5.0.3 on 2024-07-07 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("electrode", "0006_alter_electrodehistory_electrode_and_more"),
        ("warehouse", "0005_alter_mahsulot_massa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electrodehistory",
            name="customer_id",
        ),
        migrations.AddField(
            model_name="electrodehistory",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.customer",
            ),
        ),
    ]
